//Clase figura, la cual tiene como atributos x, y, id (que se ira incrementando en el contructor)
// y el contexto de la figura. Estos son atributos que toda figura deberia tener
export class Figure{
   // x;
   // y;
    id;
    ctx;

    //toda figura tendra un eje x e y
    //toda figura tendra un contexto
    constructor(ctx){
        let id = 1;
        //id += 1; //autogenerated?
        this.ctx = ctx;
    }
}